export const ERROR = 'REPORT/ERROR'
export const LOADING = 'REPORT/LOADING'
export const CLEAR_MESSAGE = 'REPORT/CLEAR_MESSAGE'

export const CREATE = 'REPORT/CREATE'
export const READ = 'REPORT/READ'
export const READ_ALL = 'REPORT/READ_ALL'
export const UPDATE = 'REPORT/UPDATE'
export const DELETE = 'REPORT/DELETE'

export const READ_REPORT_GROUPS_HEADERS_BY_ADMIN =
  'REPORT/READ_REPORT_GROUPS_HEADERS_BY_ADMIN'

export const READ_REPORTS_BY_ADMIN = 'REPORT/READ_REPORTS_BY_ADMIN'

export const READ_ACCOUNT_REPORTS_BY_ADMIN =
  'REPORT/READ_ACCOUNT_REPORTS_BY_ADMIN'

export const READ_USERS_REPORTS_BY_ADMIN = 'REPORT/READ_USERS_REPORTS_BY_ADMIN'

export const UPDATE_REPORT_ACTIVE_STATE_BY_ADMIN =
  'REPORT/UPDATE_REPORT_ACTIVE_STATE_BY_ADMIN'
