const RESOURCE = 'TERMS_AND_CONDITIONS'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_TERMS_AND_CONDITIONS = `${RESOURCE}/READ_TERMS_AND_CONDITIONS`
