const RESOURCE = `ADMINS`

export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`

export const READ_LOGO = `${RESOURCE}/READ_LOGO`
export const UPDATE_LOGO = `${RESOURCE}/UPDATE_LOGO`

export const READ_LOGO_BY_SUBDOMAIN = `${RESOURCE}/READ_LOGO_BY_SUBDOMAIN`
export const ACCEPT_TERMS_AND_CONDITIONS = `${RESOURCE}/ACCEPT_TERMS_AND_CONDITIONS`
