const RESOURCE = `USERS_GROUPS`

export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`

export const CREATE = `${RESOURCE}/CREATE`
export const READ = `${RESOURCE}/READ`
export const READ_INDEPENDENT_SECTIONS_IDS = `${RESOURCE}/READ_INDEPENDENT_SECTIONS_IDS`
export const READ_ALL = `${RESOURCE}/READ_ALL`
export const UPDATE = `${RESOURCE}/UPDATE`
export const DELETE = `${RESOURCE}/DELETE`
