export const ERROR = 'POWERBI/ERROR'
export const LOADING = 'POWERBI/LOADING'
export const CLEAR_MESSAGE = 'POWERBI/CLEAR_MESSAGE'

export const GET_ACCESS_TOKEN = 'POWERBI/GET_ACCESS_TOKEN'
export const GET_REPORT_DATA = 'POWERBI/GET_REPORT_DATA'
