const RESOURCE = 'IDENTIFICATION_DOCUMENTS'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_IDENTIFICATION_DOCUMENTS = `${RESOURCE}/READ_IDENTIFICATION_DOCUMENTS`
