const RESOURCE = 'INVOICES'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_INVOICES_BY_CONTRACT = `${RESOURCE}/READ_INVOICES_BY_CONTRACT`
export const READ_INVOICES_DETAIL_BY_CONTRACT = `${RESOURCE}/READ_INVOICES_DETAIL_BY_CONTRACT`
