export const ERROR = 'WORKSPACES/ERROR'
export const LOADING = 'WORKSPACES/LOADING'
export const CLEAR_MESSAGE = 'WORKSPACES/CLEAR_MESSAGE'

export const READ_WORKSPACES_BY_ADMIN = 'WORKSPACES/READ_WORKSPACES_BY_ADMIN'
