const RESOURCE = 'CURRENCIES'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_CURRENCIES = `${RESOURCE}/READ_CURRENCIES`
