const RESOURCE = 'CONTRACTS'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_COUNTRIES = `${RESOURCE}/READ_COUNTRIES`
export const READ_REGIONS = `${RESOURCE}/READ_REGIONS`
export const READ_ZONES = `${RESOURCE}/READ_ZONES`
