const RESOURCE = 'CONTRACTS'

export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`

export const READ_CONTRACT_BY_ADMIN = `${RESOURCE}/READ_CONTRACT_BY_ADMIN`
export const READ_CONTRACT_DETAILS_BY_ADMIN = `${RESOURCE}/READ_CONTRACT_DETAILS_BY_ADMIN`
export const UPDATE_CONTRACT = `${RESOURCE}/UPDATE_CONTRACT`
export const UPDATE_CONTRACT_DETAIL = `${RESOURCE}/UPDATE_CONTRACT_DETAIL`
